rio: 'Amazonas'  # Amazonas, Madeira, Solimoes
horizonte: 7  # 7, 14, 21

data_paths:
  loc: '\\data\\preprocessing\\demands\\'
  routes: '\\data\\preprocessing\\routes\\'
  patterns: '\\data\\preprocessing\\departure_patterns\\'

corridor_factor: 0.9
fixed_conversion: 11.76
consumption: 150
price_gnl: 1.97
price_liquid: 1.10
