rio: 'Amazonas'  # Amazonas, Madeira, Solimoes
horizonte: 7  # 7, 14, 21
num_veic: 1
capacities: [2000, 600, 400]  #  do not change

data_paths:
  loc: '\\data\\preprocessing\\demands\\'
  routes: '\\data\\preprocessing\\routes\\'
  patterns: '\\data\\preprocessing\\departure_patterns\\'
  results: '\\data\\results\\'

fixed_conversion: 11760
consumption: 150
price_gnl: 1.97
price_liquid: 1.10
