rio: 'Solimoes' # 'Amazonas', 'Madeira', 'Solimoes'

cap_max: [35, 42, 77] # [35, 42, 77] -> capacity: 2000 * 0.9 / 50 = 36
vel_media: 10 # km/h
t_carregamento: 5 # min

data_paths:
  dist: '\\data\\distances\\distance.xlsx'
  loc: '\\data\\preprocessing\\demands\\'
  routes_folder: '\\data\\preprocessing\\routes\\'
