rio: 'Amazonas' # 'Amazonas', 'Madeira', 'Solimões'

cap_max: 35 # 2000 * 0.9 / 50 = 36
vel_media: 18.52 # 10 * 1.852
t_carregamento: 0.33 # 4 * 5 / 60

data_paths:
  dist: '\\data\\distances\\distance.xlsx'
  loc: '\\data\\preprocessing\\demands\\'
  routes_folder: 'data/preprocessing/routes/'
